<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>MoonlightSuite</AssemblyName>
    <RootNamespace>MoonlightSuite</RootNamespace>
    <Version>2.0.0</Version>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**" />
    <None Remove="tests/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTabletDriver.Plugin" Version="0.6.6.2" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MoonlightSuite.Tests" />
  </ItemGroup>

</Project>
