<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>MoonlightSuite</AssemblyName>
    <RootNamespace>MoonlightSuite</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTabletDriver.Plugin" Version="0.6.6.2" />
  </ItemGroup>

</Project>